# Generated by Django 4.0.4 on 2022-05-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='User')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('status', models.CharField(default='review', max_length=255, verbose_name='Status')),
            ],
        ),
    ]
